### ISSUE TITLE
Dagligt forbrug ?

### ISSUE THREAD

**Issue by nerdalertdk** [JonasPed/homeassistant-eloverblik#61]
Hej,

Er det mulig at få et dagligt forbrug?
Går ikke så meget op i hvad jeg bruger i timen, men mere hvad jeg bruger om dagen ?
Kan se dataen er inde på eloverblik

![image](https://user-images.githubusercontent.com/3426495/199025200-669c01eb-4549-48c8-99c9-4e7f0514ddfb.png)

**Comment by JonasPed** [comment]
Hej

Det har du allerede i total sensoren. Der er to total sensoren. En for år til dato og en for seneste dags forbrug.

**Comment by nerdalertdk** [comment]
Måske en som kan hjælpe med jo chart kode, for kan ikke få den til at vise måned forbrug

```
type: custom:apexcharts-card
graph_span: 365d
update_interval: 1d
span:
  end: year
header:
  show: true
  title: El forbrug
  show_states: true
  colorize_states: true
apex_config:
  xaxis:
    tickAmount: 12
    tickPlacement: between
    type: datetime
    labels:
      datetimeFormatter:
        year: yy
        month: MMM
        day: dd MMM
        hour: HH
    axisTicks:
      height: 6
all_series_config:
  show:
    legend_value: false
    datalabels: false
    extremas: true
    in_brush: false
  float_precision: 1
  invert: false
yaxis:
  - decimals: 1
series:
  - entity: sensor.eloverblik_energy_total_year
    type: column
    name: Forbrug
    group_by:
      duration: 1month
      func: sum

```
